### ISSUE TITLE
when a connection is invalid the catch handler is not called

### ISSUE THREAD

**Issue by geoffreysamper** [Azure/azure-event-hubs-node#116]
**Describe the bug**
When the hostname is invalid (ex hostname has a typo) I should expect that my catch handler is called

**To Reproduce**
- copy code to script 
- install the eventhub sdk for node
- replace EVENTHUBNAME by the eventhub name
- replace EVENTHUBCONNECTIONSTRING with a connectionstring and introduce a type in the hostname
- run the follow code
```const { EventHubClient}= require('azure-event-hubs');
const connectionstring = "<EVENTHUBCONNECTIONSTRING>"
const eventhubEntityName = "<EVENTHUBNAME>"
const sb= "<eventhubconnectionstring">;
const name = "<eventEntityPath>"
const client = EventHubClient.createFromConnectionString(sb,name);
async function main() {
    const payload ="hello"
    const data = { body: payload };
    return  await client.send(data, "1");
    
}

main().catch((err) => {
    console.log('I expect to see this line');
    console.log(err);
}).then(function() {
    console.log("message sent successfully.");

});
```

**Expected behavior**
The catch function should be called and the console contains `expect to see this line`.

**Package-name**: **azure-event-hubs** 
**Package-version**: 0.2.5
**node.js version**: node 10.6.0
**OS name and version**: Linux mint 18

**Comment by amarzavery** [comment]
@geoffreysamper - The SDK is behaving as expected. Since you gave an invalid connectionstring, this line `const client = EventHubClient.createFromConnectionString(sb,name);` threw an error. `main()` was never called.

I see the following error
```js
Error: 'endpoint' is a required property of ConnectionConfig.
    at Object.validate (/Users/amarz/sdk/rh/final/azure-event-hubs-node/client/lib/amqp-common/connectionConfig.ts:77:13)
    at Object.create (/Users/amarz/sdk/rh/final/azure-event-hubs-node/client/lib/connectionContext.ts:100:22)
    at new EventHubClient (/Users/amarz/sdk/rh/final/azure-event-hubs-node/client/lib/eventHubClient.ts:110:39)
    at Function.createFromConnectionString (/Users/amarz/sdk/rh/final/azure-event-hubs-node/client/lib/eventHubClient.ts:296:12)
    at Object.<anonymous> (/Users/amarz/sdk/rh/final/azure-event-hubs-node/client/examples/t.ts:5:31)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:403:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:406:12)
    at Module.load (module.js:565:32)
```

**Comment by amarzavery** [comment]
I would recommend something like this in your script
```js
const { EventHubClient } = require("azure-event-hubs");

const sb = "Endpoint=someendpoint;SharedAccessKeyName=Something;SharedAccessKey=SomethingSecret";
const name = "<eventEntityPath>";
const client = EventHubClient.createFromConnectionString(sb, name);
async function main() {
  const payload = "hello"
  const data = { body: payload };
  return await client.send(data, "1");

}

main().then(function () {
  console.log("message sent successfully.");
}).catch((err) => {    // The catch should be after the `.then()`
  console.log('I expect to see this line');
  console.log(err);
});
```

**Comment by amarzavery** [comment]
Or have the `const client = EventHubClient.createFromConnectionString(sb,name);` inside the `main()` function.

**Comment by geoffreysamper** [comment]
@amarzavery I review my error tonight i'm in utc+1

**Comment by amarzavery** [comment]
Closing this issue for now. Please feel free to reopen if you still have questions.
