### ISSUE TITLE
MessagingEntityNotFoundError: The messaging entity could not be found.

### ISSUE THREAD

**Issue by makoit** [Azure/azure-event-hubs-node#133]
In the past I used the lib "azure-event-hubs": "0.0.8" to receive my messages from my event hub. It wrote my client in javascript like this:

```
var connectionString = 'Endpoint=sb://*********';
var eventHubPath = '*****';
var consumerGroup = '$default';

//EVENT-HUB Connection
var eventHubClient = EventHubClient.fromConnectionString(connectionString, eventHubPath);

eventHubClient.getPartitionIds().then(function (partitionIds) { console.log(partitionIds) });

eventHubClient.open()
    .then(eventHubClient.getPartitionIds.bind(eventHubClient))
    .then(function (partitionIds) {
        return Promise.map(partitionIds, function (partitionId) {
            return eventHubClient.createReceiver(consumerGroup, partitionId, { 'startAfterTime': Date.now() }).then(function (receiver) {
                receiver.on('errorReceived', print.printError);
                receiver.on('message', print.printMessage);
            });
        });
    })
 .catch(print.printError);
```
This works fine for me. I got all my messages.

Now I want to rewrite my service in the same way in typescript.  I can see you rewrote the lib from scratch in typescript. 
So I used your receive streaming example for my service:

```
const connectionString: string = "Endpoint=sb://*******";
const eventHubPath: string = "*****";
const consumerGroup = "$default";

export async function main() {

    const client = EventHubClient.createFromConnectionString(connectionString, eventHubPath);

    client.getPartitionIds().then((partitionIds) => {
        console.log(partitionIds);
    }).catch((error) => {
        console.error(error);
    });

    const onMessage: OnMessage = async (eventData: any) => {
        console.log(">>>>> Actual message:", eventData.body);
    };

    const onError: OnError = (err: MessagingError | Error) => {
        console.log(">>>>> Error occurred: ", err);
    };

    const options: ReceiveOptions = {
        consumerGroup,
        enableReceiverRuntimeMetric: true,
        eventPosition: EventPosition.fromEnqueuedTime(Date.now()),
    };

    const partitionId = "0";
    const receiveHandler = client.receive(partitionId, onMessage, onError, options);

    console.log("Receivehandler name: ", receiveHandler.name);
    console.log("Receivehandler partition ID: ", receiveHandler.partitionId);
}

```
If I run this code I get these two erros:

Error 1:

```
{ MessagingEntityNotFoundError: The messaging entity 'sb://*********/$management' could not be found. TrackingId:***********, SystemTracker:********/$management, 

...
  name: 'MessagingEntityNotFoundError',
  translated: true,
  retryable: false,
  info: undefined,
  condition: 'amqp:not-found' }
```

Here I tried to read out the partition id's. In my "old" code it worked. Now it doesn't work. I don't have a the consumer group $management.

Error 2:

```
>>>>> Error occurred:  { MessagingEntityNotFoundError: The messaging entity 'sb://**********$default/Partitions/0' could not be found. TrackingId:*****, SystemTracker:*****/ConsumerGroups/$default/Partitions/0, 
.....
  name: 'MessagingEntityNotFoundError',
  translated: true,
  retryable: false,
  info: undefined,
  condition: 'amqp:not-found' }
```

Here I mapped the receiver to my client. But the partition cannot be found. With my "old" code I read out my partitions:

`[ '0', '1' ]`.

Hope someone can help me.

**Comment by amarzavery** [comment]
I just ran the sample from the repo and everything worked fine

```ts
Amars-MBP:client amarz$ ts-node examples/getHubRuntimeInfo.ts
test1
RuntimeInfo:  { path: 'testfoo',
  createdAt: 2018-05-08T18:51:07.770Z,
  partitionCount: 3,
  partitionIds: [ '0', '1', '2' ],
  type: 'com.microsoft:eventhub' }
Partition Information:  { beginningSequenceNumber: 237854,
  hubPath: 'testfoo',
  lastEnqueuedOffset: '34366219744',
  lastEnqueuedTimeUtc: 2018-08-07T21:48:58.989Z,
  lastSequenceNumber: 237854,
  partitionId: '0',
  type: 'com.microsoft:partition' }
```

I ran the streamingReceiver example as well, after sending some messages and changing the option`eventposition: EventPosition.fromStart()`.

```ts
Amars-MBP:client amarz$ ts-node examples/streamingReceive.ts
rcvHandler:  a3ec23ba-b79c-4eb9-b4cd-fe6531745e11
>>> EventDataObject:  { body: 'Hello World EventHub!!',
  _raw_amqp_mesage: {"delivery_annotations":{"last_enqueued_sequence_number":237855,"last_enqueued_offset":"34366219896","last_enqueued_time_utc":1534788561630,"runtime_info_retrieval_time_utc":1534788617199},"message_annotations":{"x-opt-sequence-number":237854,"x-opt-offset":"34366219744","x-opt-enqueued-time":1533678538989},"message_id":"be5da050-a9b6-4903-a8c1-6b345c726d54","body":{"typecode":117,"content":{"type":"Buffer","data":[34,72,101,108,108,111,32,87,111,114,108,100,32,69,118,101,110,116,72,117,98,33,33,34]}}},
  annotations:
   { 'x-opt-sequence-number': 237854,
     'x-opt-offset': '34366219744',
     'x-opt-enqueued-time': 1533678538989 },
  sequenceNumber: 237854,
  enqueuedTimeUtc: 2018-08-07T21:48:58.989Z,
  offset: '34366219744',
  properties: { message_id: 'be5da050-a9b6-4903-a8c1-6b345c726d54' },
  lastEnqueuedOffset: '34366219896',
  lastSequenceNumber: 237855,
  lastEnqueuedTime: 2018-08-20T18:09:21.630Z,
  retrievalTime: 2018-08-20T18:10:17.199Z }
### Actual message: Hello World EventHub!!
>>> EventDataObject:  { body: 'Hello World!!',
  _raw_amqp_mesage: {"delivery_annotations":{"last_enqueued_sequence_number":237855,"last_enqueued_offset":"34366219896","last_enqueued_time_utc":1534788561630,"runtime_info_retrieval_time_utc":1534788617199},"message_annotations":{"x-opt-sequence-number":237855,"x-opt-offset":"34366219896","x-opt-enqueued-time":1534788561630},"message_id":"ff759704-c09a-4fc9-9c9e-38ebecb2768f","body":{"typecode":117,"content":{"type":"Buffer","data":[34,72,101,108,108,111,32,87,111,114,108,100,33,33,34]}}},
  annotations:
   { 'x-opt-sequence-number': 237855,
     'x-opt-offset': '34366219896',
     'x-opt-enqueued-time': 1534788561630 },
  sequenceNumber: 237855,
  enqueuedTimeUtc: 2018-08-20T18:09:21.630Z,
  offset: '34366219896',
  properties: { message_id: 'ff759704-c09a-4fc9-9c9e-38ebecb2768f' },
  lastEnqueuedOffset: '34366219896',
  lastSequenceNumber: 237855,
  lastEnqueuedTime: 2018-08-20T18:09:21.630Z,
  retrievalTime: 2018-08-20T18:10:17.199Z }
### Actual message: Hello World!!
^C
Amars-MBP:client amarz$
```

**Comment by makoit** [comment]
@amarzavery thanks for your fast response!

I cloned the repo and tried the sample "getHubRuntimeInfo.ts". 

The following code is my first try, I only changed the "connectionString" and the "entityPath".

```
import { EventHubClient } from "../lib";
import * as dotenv from "dotenv";
dotenv.config();

const connectionString = "Endpoint=sb://***;SharedAccessKeyName=***;SharedAccessKey=***;EntityPath=***";
const entityPath = "***";
const str = process.env[connectionString] || "";
const path = process.env[entityPath] || "";
console.log("connection string: ", str);
console.log("path: ", path );

async function main(): Promise<void> {
  const client = EventHubClient.createFromConnectionString(str, path);
  const info = await client.getHubRuntimeInformation();
  console.log("RuntimeInfo: ", info);
  const pInfo = await client.getPartitionInformation("0");
  console.log("Partition Information: ", pInfo);
  await client.close();
}

main().catch((err) => {
  console.log("error: ", err);
});

```
When I run the code I get this error:

```
$ ts-node examples/getHubRuntimeInfo.ts
connection string:
path:
error:  Error: 'connectionString' is a required parameter and must be of type: 'string'.
    at Function.EventHubClient.createFromConnectionString (C:\DEV\Local\azure-event-hubs-node\client\lib\eventHubClient.js:336:19)
    at main (C:\DEV\Local\azure-event-hubs-node\client\examples\getHubRuntimeInfo.ts:13:33)
    at Object.<anonymous> (C:\DEV\Local\azure-event-hubs-node\client\examples\getHubRuntimeInfo.ts:21:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (C:\Users\***\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\***\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

I think here are these two lines my problem:

```
const str = process.env[connectionString] || "";
const path = process.env[entityPath] || "";
```
I logged the "str" and "path" and they are empty....

Then I modified the code and tried this (without these two lines above):

```
import { EventHubClient } from "../lib";
import * as dotenv from "dotenv";
dotenv.config();

const connectionString = "Endpoint=sb://***/;SharedAccessKeyName=***;SharedAccessKey=***=;EntityPath=***";
const entityPath = "***";


async function main(): Promise<void> {
  const client = EventHubClient.createFromConnectionString(connectionString, entityPath);
  const info = await client.getHubRuntimeInformation();
  console.log("RuntimeInfo: ", info);
  const pInfo = await client.getPartitionInformation("0");
  console.log("Partition Information: ", pInfo);
  await client.close();
}

main().catch((err) => {
  console.log("error: ", err);
});

```

Now I get this error:

```
$ ts-node examples/getHubRuntimeInfo.ts
error:  { MessagingEntityNotFoundError: The messaging entity 'sb://***/$management' could not be found. TrackingId:*** SystemTracker:***/$management, Timestamp:8/21/2018 5:48:21 AM
    at new MessagingError (C:\DEV\Local\azure-event-hubs-node\client\lib\amqp-common\errors.js:387:28)
    at Object.translate (C:\DEV\Local\azure-event-hubs-node\client\lib\amqp-common\errors.js:460:21)
    at Receiver.messageCallback (C:\DEV\Local\azure-event-hubs-node\client\lib\amqp-common\requestResponseLink.js:135:42)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.link.dispatch (C:\DEV\Local\azure-event-hubs-node\client\node_modules\rhea\lib\link.js:59:37)
    at Incoming.on_transfer (C:\DEV\Local\azure-event-hubs-node\client\node_modules\rhea\lib\session.js:357:22)
    at Session.on_transfer (C:\DEV\Local\azure-event-hubs-node\client\node_modules\rhea\lib\session.js:728:19)
    at Connection.(anonymous function) [as on_transfer] (C:\DEV\Local\azure-event-hubs-node\client\node_modules\rhea\lib\connection.js:689:30)
    at c.dispatch (C:\DEV\Local\azure-event-hubs-node\client\node_modules\rhea\lib\types.js:909:33)
  name: 'MessagingEntityNotFoundError',
  translated: true,
  retryable: false,
  info: undefined,
  condition: 'amqp:not-found' }
```

In the error I see the "$management" consumer group. But I only use the "$default" consumer group.

Maybe the problem is the connectionString and the entityPath?

**Comment by amarzavery** [comment]
- Have you created the EventHub namespace and an EventHub within that namespace? 
- Are you providing the right connectionstring for the right EventHub?
- Can you provide the debug logs? You can set the environment variable like this
```
set DEBUG=azure*,rhea*,-rhea:raw,-rhea:message,-azure:amqp-common:datatransformer
```

Do not mask (***) anything else apart from the SharedAcessKeyName and the SharedAccessKeyValue. It is ok to share the eventhub namespace and the eventhub. You can delete it later.

**Comment by amarzavery** [comment]
The hub runtime info and the partition runtime info (metadata about the eventhub and the partition) are fetched from the $management endpoint off the eventhub. It has got nothing to do with the $default consumer group.

**Comment by makoit** [comment]
@amarzavery 

I solved the problem. It was my connectionString and the entityPath. How you can see in the code above I also had the entityPath at the end of my connectionString. I cut it out and now the "getHubRuntimeInfo.ts" and the "streamingReceive.ts" works correctly. In my "old" javascript code the connectionString worked in this way. So thats why I used the same form again. 

Sorry for wasting your time!

I have one question more, how can I use the receive example within a ts class. So I want to implement the new service more modular with classes. But I'm not sure how I can use the lib inside of a class (because of the events).

**Comment by makoit** [comment]
Yes that was the idea. I want to use the class "EventHubClient" for creating muliple event-hub-clients. Then I want create a new event-hub-client in a "main-method" and set there the receice event handler. I think in this way it will work for me!

Thank you for your great help! 
It's nice to see how good the help is here!

**Comment by amarzavery** [comment]
>  I want to use the class "EventHubClient" for creating muliple event-hub-clients. 

This is fine. However, it is not necessary. Every instance of an Eventhub client will create an amqp connection. You may not want that many amqp connections.

You can rather create a singleton instance of an eventhub client and then call client.receive(..) as and when required. This will give you a reference to the ReceiveHandler. You can store those references in an object/dictionary and then choose to stop the receiver whenever you deem fit.

The Eventhub service allows you to create upto 5 receivers listening to a partition from a consumer group. The moment you try to create a 6th one, the service will throw an error with an appropriate message. The Eventhub client internally caches those receivers for you.

Note: It is still perfectly fine to create multiple EH Client instances, if that is a requirement.

> Thank you for your great help!
> It's nice to see how good the help is here!

You are very welcome :).

**Comment by amarzavery** [comment]
closing this issue since the problem has been resolved.
