### ISSUE TITLE
The message container is being closed

### ISSUE THREAD

**Issue by lulzmachine** [Azure/azure-event-hubs-node#26]
Hey!

We are currently using `"azure-event-hubs": "0.0.8"` in our node project. After letting it run for some hours, we sometimes encounter this error:

```
Error from event hub: { Error: The message container is being closed (94995). TrackingId:<sometrackingid>, SystemTracker:NoSystemTracker, Timestamp:5/23/2017 4:14:51 PM
at Object.translateError [as translate] (/usr/src/app/node_modules/azure-event-hubs/lib/errors.js:37:15)
at ReceiverLink.onErrorReceived (/usr/src/app/node_modules/azure-event-hubs/lib/receiver.js:32:39)
at emitOne (events.js:101:20)
at ReceiverLink.emit (events.js:188:7)
at ReceiverLink.Link._detached (/usr/src/app/node_modules/amqp10/lib/link.js:221:10)
at ReceiverLink.Link._detachReceived (/usr/src/app/node_modules/amqp10/lib/link.js:204:8)
at Session._processDetachFrame (/usr/src/app/node_modules/amqp10/lib/session.js:335:45)
at Session._processFrame (/usr/src/app/node_modules/amqp10/lib/session.js:302:61)
at Connection._processFrameEH (/usr/src/app/node_modules/amqp10/lib/session.js:186:49)
at emitOne (events.js:101:20)
at Connection.emit (events.js:188:7)
at Connection._receiveAny (/usr/src/app/node_modules/amqp10/lib/connection.js:426:12)
at Connection._receiveData (/usr/src/app/node_modules/amqp10/lib/connection.js:357:8)
at TlsTransport.<anonymous> (/usr/src/app/node_modules/amqp10/lib/connection.js:515:38)
at emitOne (events.js:96:13)
at TlsTransport.emit (events.js:188:7)
transport:
{ AmqpProtocolError: com.microsoft:container-close:The message container is being closed (94995). TrackingId:<sometrackingid>, SystemTracker:NoSystemTracker, Timestamp:5/23/2017 4:14:51 PM
at Object.errors.wrapProtocolError (/usr/src/app/node_modules/amqp10/lib/errors.js:10:12)
at ReceiverLink.Link._detached (/usr/src/app/node_modules/amqp10/lib/link.js:221:42)
at ReceiverLink.Link._detachReceived (/usr/src/app/node_modules/amqp10/lib/link.js:204:8)
at Session._processDetachFrame (/usr/src/app/node_modules/amqp10/lib/session.js:335:45)
at Session._processFrame (/usr/src/app/node_modules/amqp10/lib/session.js:302:61)
at Connection._processFrameEH (/usr/src/app/node_modules/amqp10/lib/session.js:186:49)
at emitOne (events.js:101:20)
at Connection.emit (events.js:188:7)
at Connection._receiveAny (/usr/src/app/node_modules/amqp10/lib/connection.js:426:12)
at Connection._receiveData (/usr/src/app/node_modules/amqp10/lib/connection.js:357:8)
at TlsTransport.<anonymous> (/usr/src/app/node_modules/amqp10/lib/connection.js:515:38)
at emitOne (events.js:96:13)
at TlsTransport.emit (events.js:188:7)
at TLSSocket.<anonymous> (/usr/src/app/node_modules/amqp10/lib/transport/tls_transport.js:29:49)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
name: 'AmqpProtocolError',
message: 'com.microsoft:container-close:The message container is being closed (94995). TrackingId:<sometrackingid>, SystemTracker:NoSystemTracker, Timestamp:5/23/2017 4:14:51 PM',
condition: 'com.microsoft:container-close',
description: 'The message container is being closed (94995). TrackingId:<sometrackingid>, SystemTracker:NoSystemTracker, Timestamp:5/23/2017 4:14:51 PM',
errorInfo: {} } }
```

(I just removed the tracking id).

The code looks something like this:
```
eventHubClient.open()
  .then(() => {
    return eventHubClient.getPartitionIds()
  })
  .then(partitionIds => {
    return partitionIds.map(partitionId => {
      return eventHubClient.createReceiver('$Default', partitionId, {'startAfterTime': Date.now()}).then(receiver => {
        receiver.on('errorReceived', (err) => {
          log.info('Error from event hub: ', err)
        })
```

After that, the code still runs, but we are not getting any messages or errors. The error appeared 3 times (we have 4 partititons).

I think for now we'll make sure to restart the process when this happens, to reset. But that's not optimal

**Comment by willin** [comment]
same error, mark.

**Comment by Frankz** [comment]
Hello, 
Closing the connection when the error appears works for me

**Comment by amarzavery** [comment]
@lulzmachine @willin @Frankz -  We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
